import type { Story, Source, TopicPreference, RadarStats, UserSetting } from '../types';

export const FALLBACK_STORIES: Story[] = [
  {
    id: 1,
    source_id: 1,
    source_name: 'Anthropic Research & News',
    title: 'Anthropic Unveils Claude 3.7 Sonnet with Dynamic Extended Thinking',
    normalized_title: 'anthropic unveils claude 3 7 sonnet dynamic extended thinking',
    headline: 'Claude 3.7 Sonnet introduces hybrid instant and extended reasoning API controls',
    summary:
      'Anthropic released Claude 3.7 Sonnet, the industry-first hybrid reasoning model providing continuous control over reasoning budgets. Practitioners can dynamically choose between sub-second inference and deep multi-step thinking traces for complex code synthesis and architectural evaluations.',
    why_it_matters: [
      'Establishes a new paradigm in frontier model architecture by unifying fast inference and reasoning tokens into a single unified API endpoint.',
    ],
    original_url: 'https://www.anthropic.com/news/claude-3-7-sonnet',
    canonical_url: 'https://www.anthropic.com/news/claude-3-7-sonnet',
    category: 'LLMs',
    companies: ['Anthropic'],
    technologies: ['Claude 3.7', 'Extended Thinking', 'Reasoning APIs'],
    topics: ['Reasoning Models', 'LLMs', 'Developer Tools'],
    importance_score: 96.0,
    novelty_score: 94.0,
    technical_score: 92.0,
    is_breaking: true,
    is_saved: false,
    is_ai_related: true,
    rank_score: 98.4,
    published_at: new Date(Date.now() - 3600 * 1000 * 3).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    source_id: 2,
    source_name: 'DeepSeek Research',
    title: 'DeepSeek Publishes Landmark R1 Paper on Pure RL Reasoning Without Supervised Warmup',
    normalized_title: 'deepseek publishes landmark r1 paper on pure rl reasoning',
    headline: 'DeepSeek open-weights R1 demonstrates pure reinforcement learning post-training',
    summary:
      'DeepSeek published technical documentation detailing the architecture of DeepSeek-R1. The research confirms that large language models can develop complex reasoning behaviors, reflection, and self-correction purely through reinforcement learning without initial supervised fine-tuning.',
    why_it_matters: [
      'Proves that frontier reasoning capabilities can emerge through large-scale RL incentives, significantly lowering the data barrier for open-source AI teams.',
    ],
    original_url: 'https://arxiv.org/abs/2501.12948',
    canonical_url: 'https://arxiv.org/abs/2501.12948',
    category: 'Research',
    companies: ['DeepSeek'],
    technologies: ['DeepSeek-R1', 'Pure RL', 'GRPO', 'Open-Weights'],
    topics: ['Reinforcement Learning', 'Reasoning Models', 'Open-Weights'],
    importance_score: 95.0,
    novelty_score: 98.0,
    technical_score: 96.0,
    is_breaking: true,
    is_saved: false,
    is_ai_related: true,
    rank_score: 97.2,
    published_at: new Date(Date.now() - 3600 * 1000 * 6).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    source_id: 3,
    source_name: 'Google DeepMind Blog',
    title: 'Google DeepMind Unveils Gemini Robotics 2 for Whole-Body Intelligence and Multi-Robot Collaboration',
    normalized_title: 'google deepmind unveils gemini robotics 2 whole body intelligence',
    headline: 'Gemini Robotics 2 scales vision-language-action models to complex multi-robot tasks',
    summary:
      'Google DeepMind announced Gemini Robotics 2, an end-to-end vision-language-action model trained across physical simulations and real-world environments. The system enables real-time dexterity, tool coordination, and spatial reasoning across diverse robotic form factors.',
    why_it_matters: [
      'Bridges high-level multimodal reasoning with low-level actuator control, accelerating the deployment of general-purpose robots in logistics and manufacturing.',
    ],
    original_url: 'https://deepmind.google/discover/blog/gemini-robotics-2/',
    canonical_url: 'https://deepmind.google/discover/blog/gemini-robotics-2/',
    category: 'Hardware',
    companies: ['Google', 'DeepMind'],
    technologies: ['Gemini Robotics 2', 'VLA', 'Physical Intelligence'],
    topics: ['Robotics', 'Multimodal', 'Embodied AI'],
    importance_score: 93.0,
    novelty_score: 91.0,
    technical_score: 89.0,
    is_breaking: false,
    is_saved: false,
    is_ai_related: true,
    rank_score: 92.5,
    published_at: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    source_id: 4,
    source_name: 'Microsoft Research AI',
    title: 'Orchard: An Open Framework for Scalable Agentic AI Workflows',
    normalized_title: 'orchard an open framework for scalable agentic ai workflows',
    headline: 'Microsoft Research releases Orchard for deterministic multi-agent state orchestration',
    summary:
      'Microsoft Research released Orchard, an open-source framework designed to build resilient, distributed multi-agent systems with formal state checkpointing and Model Context Protocol (MCP) integrations.',
    why_it_matters: [
      'Standardizes production agent architectures with enterprise-grade error recovery and reproducible tool execution pipelines.',
    ],
    original_url: 'https://www.microsoft.com/en-us/research/blog/orchard-agentic-framework/',
    canonical_url: 'https://www.microsoft.com/en-us/research/blog/orchard-agentic-framework/',
    category: 'AI Agents',
    companies: ['Microsoft', 'Anthropic'],
    technologies: ['Orchard', 'MCP', 'Agent Workflows'],
    topics: ['AI Agents', 'Developer Tools', 'Open Source'],
    importance_score: 91.0,
    novelty_score: 86.0,
    technical_score: 90.0,
    is_breaking: false,
    is_saved: false,
    is_ai_related: true,
    rank_score: 90.1,
    published_at: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    source_id: 5,
    source_name: 'NVIDIA Technical Blog',
    title: 'NVIDIA TensorRT-LLM 0.18 Accelerates Speculative Decoding and KV-Cache Compression',
    normalized_title: 'nvidia tensorrt llm 0 18 accelerates speculative decoding',
    headline: 'TensorRT-LLM 0.18 achieves 3.2x throughput increase on Blackwell and Hopper architectures',
    summary:
      'NVIDIA announced TensorRT-LLM 0.18, featuring dynamic KV-cache eviction kernels, speculative token verification, and FP4 quantization support. The release drops latency by up to 60% for long-context agentic reasoning workloads.',
    why_it_matters: [
      'Directly reduces serving costs and GPU memory footprint for enterprise production inference deployments.',
    ],
    original_url: 'https://developer.nvidia.com/blog/tensorrt-llm-0-18-speculative-decoding/',
    canonical_url: 'https://developer.nvidia.com/blog/tensorrt-llm-0-18-speculative-decoding/',
    category: 'Hardware',
    companies: ['NVIDIA'],
    technologies: ['TensorRT-LLM', 'Blackwell', 'FP4', 'KV-Cache'],
    topics: ['Inference', 'Hardware', 'Developer Tools'],
    importance_score: 89.0,
    novelty_score: 85.0,
    technical_score: 94.0,
    is_breaking: false,
    is_saved: false,
    is_ai_related: true,
    rank_score: 88.7,
    published_at: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
    created_at: new Date().toISOString(),
  },
];

export const FALLBACK_STATS: RadarStats = {
  total_sources: 10,
  active_sources: 10,
  total_stories: 162,
  breaking_stories_count: 3,
  saved_stories_count: 4,
  total_interactions: 42,
  is_scanning: false,
  last_scan_time: new Date().toISOString(),
  category_distribution: [
    { category: 'AI Agents', count: 48 },
    { category: 'LLMs', count: 42 },
    { category: 'Research', count: 36 },
    { category: 'Hardware', count: 24 },
    { category: 'Developer Tools', count: 12 },
  ],
  top_topics: ['Reasoning Models', 'AI Agents', 'Open-Weights', 'Robotics', 'Hardware'],
};

export const FALLBACK_TOPICS: TopicPreference[] = [
  { topic: 'AI Agents', weight: 1.65, positive_count: 12, negative_count: 1, updated_at: new Date().toISOString() },
  { topic: 'Reasoning Models', weight: 1.55, positive_count: 10, negative_count: 0, updated_at: new Date().toISOString() },
  { topic: 'LLMs', weight: 1.40, positive_count: 8, negative_count: 2, updated_at: new Date().toISOString() },
  { topic: 'Open-Weights', weight: 1.30, positive_count: 7, negative_count: 1, updated_at: new Date().toISOString() },
  { topic: 'Developer Tools', weight: 1.25, positive_count: 6, negative_count: 2, updated_at: new Date().toISOString() },
  { topic: 'Robotics', weight: 1.15, positive_count: 4, negative_count: 1, updated_at: new Date().toISOString() },
  { topic: 'Hardware', weight: 1.10, positive_count: 3, negative_count: 1, updated_at: new Date().toISOString() },
];

export const FALLBACK_SETTINGS: UserSetting = {
  user_id: 'default_user',
  gemini_model: 'gemini-3.5-flash-lite',
  has_custom_api_key: false,
  min_importance_threshold: 65.0,
  auto_scan_enabled: true,
};

export const FALLBACK_SOURCES: Source[] = [
  {
    id: 1,
    name: 'Anthropic Research & News',
    url: 'https://www.anthropic.com/news/feed.xml',
    category: 'Lab',
    feed_type: 'rss',
    is_active: true,
    last_scanned_at: new Date().toISOString(),
    failure_count: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'OpenAI News & Announcements',
    url: 'https://openai.com/news/rss.xml',
    category: 'Lab',
    feed_type: 'rss',
    is_active: true,
    last_scanned_at: new Date().toISOString(),
    failure_count: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'Google DeepMind Blog',
    url: 'https://deepmind.google/blog/rss.xml',
    category: 'Lab',
    feed_type: 'rss',
    is_active: true,
    last_scanned_at: new Date().toISOString(),
    failure_count: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Hugging Face Engineering',
    url: 'https://huggingface.co/blog/feed.xml',
    category: 'Open Source',
    feed_type: 'rss',
    is_active: true,
    last_scanned_at: new Date().toISOString(),
    failure_count: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'ArXiv CS.AI Artificial Intelligence',
    url: 'https://rss.arxiv.org/rss/cs.AI',
    category: 'Research',
    feed_type: 'rss',
    is_active: true,
    last_scanned_at: new Date().toISOString(),
    failure_count: 0,
    created_at: new Date().toISOString(),
  },
];
